account/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'account'

urlpatterns = [
    path('register', views.register, name='register'),
    path('signin', views.signin, name='signin'),
    path('validate-username', csrf_exempt(views.validate_username), name='validate-username'),
    path('validate-email', csrf_exempt(views.validate_email), name='validate-email'),
    path('update-profile', views.update_profile, name='update-profile')
]

meal/urls.py
from django.urls import path
from . import views

app_name = 'meal'


urlpatterns = [
    path('', views.meal_list, name='home'),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meal.urls', namespace='meal')),
    path('account/', include('account.urls', namespace='account'))
]

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>rms {% block title %}{% endblock %}</title>
    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">


  </head>
  <body>
    
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav my-2 my-lg-0">
          {% if user.id is not None %}
          <li>
            <span>
          <img src="{% if profile.avatar %}{{ profile.avatar.url }}{% else %}{% static 'images/userimage.png' %}{% endif %}" style="height:40px; border-radius:30%;"> -->
          </span>
            <a class="nav-link" href="{% url 'account:logout' %}">logout</a>
           </li>
           {% else %} 
        
           <li class="nav-item mr-sm-2"><a class="nav-link" href="{% url 'account:signin' %}">Login</a></li>
           <li class="nav-item mr-sm-2"><a class="nav-link" href="{% url 'account:register' %}">Signup</a></li>

          {% endif %}
          
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

<main role="main" class="container mt-5">
{% block content %}

{% endblock %}

</main>


    {% include '_partials/_scripts.html' %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script> 
    {% include '_partials/_timer.html' %}
  </body>
</html>

templates/base_auth.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Restaurant {% block title %}{% endblock %}</title>
    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

  
  </head>
  <body>
    
<main role="main" class="container">
{% block content %}

{% endblock %}

</main>


    {% include '_partials/_scripts.html' %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    
  
  </body>
</html>